# .github/actions/wheels/action.yml
name: "Build Wheels"
description: "Build wheels using cibuildwheel"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - run: pip install cibuildwheel
      shell: bash

    - name: Set Python version tag
      id: py-tag
      shell: bash
      run: echo "tag=${PYTHON_VERSION//.}" >> $GITHUB_OUTPUT
      env:
        PYTHON_VERSION: ${{ matrix.python-version }}

    - name: Build wheels
      shell: ${{ runner.os == 'Windows' && 'cmd' || 'bash' }}
      run: |
        echo "Start building wheels"
        cibuildwheel --output-dir wheelhouse
      env:
        CIBW_SKIP: "pp*"
        CIBW_BUILD: "cp${{ steps.py-tag.outputs.tag }}-*"
        CIBW_VERBOSE: "1"
        CIBW_ENVIRONMENT_WINDOWS: >
          CL=/DM_PI=3.14159265358979323846

    - uses: actions/upload-artifact@v4
      with:
        name: wheels-${{ matrix.python-version }}-${{ matrix.os }}
        path: wheelhouse/*.whl