# .github/actions/publish/action.yml
name: "Publish to PyPI"
description: "Publish built wheels to PyPI"
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: wheels-Linux
        path: dist
    - uses: actions/download-artifact@v4
      with:
        name: wheels-Windows
        path: dist
    - uses: actions/download-artifact@v4
      with:
        name: wheels-macOS
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist
        use-docker: false