# .github/actions/publish/action.yml
name: "Publish to PyPI"
description: "Publish built wheels to PyPI"
runs:
  using: "composite"
  steps:
    - uses: actions/download-artifact@v4
      with:
        name: wheels-ubuntu-22.04
        path: dist
    - uses: actions/download-artifact@v4
      with:
        name: wheels-windows-latest
        path: dist
    - uses: actions/download-artifact@v4
      with:
        name: wheels-macos-latest
        path: dist

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
