# .github/workflows/release.yml
name: Release

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    environment: Prod
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/version
        with:
          part: patch
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}

  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    environment: Prod
    needs: version
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-22.04, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
      - uses: ./.github/actions/wheels
  
  publish:
    runs-on: ubuntu-22.04
    environment: Prod
    needs: wheels
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/publish
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}